#!/bin/sh

set -eu

./fling -r 12765 > flung.out &
sleep 1

dd status=none if=/dev/urandom bs=10247 count=102400 | tee fling.in | ./fling -vp localhost 12765
cmp fling.in flung.out
rm fling.in flung.out
echo OK
